apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ddos-backend-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ddos-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ddos-collector-pdb
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ddos-collector
